# -*- coding: utf-8 -*-
"""day12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGHqJzrMAKSuU7GRang6DDj2cc2NGkpi
"""

import pandas as pd
import random
categories=["manager","senior","junior"]
data=[random.choice(categories) for _ in range(20)]
s=pd.Series(data)
print(s)

import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
#1.Create series
data=["manager","junior","senior","manager","senior",
        "junior","manager","senior","junior","manager",
        "senior","junior","manager","senior","junior",
        "manager","senior","junior","manager","senior"]
s=pd.Series(data)
#2.Label Encoding
le=LabelEncoder()
label_encoded=le.fit_transform(s)
print(label_encoded)
#3.One-Hot Encoding
onehot=OneHotEncoder(sparse_output=False)
onehot_encoded=onehot.fit_transform(s.values.reshape(-1,1))
print(onehot_encoded)

import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
df=pd.read_csv("loan_approved.csv")
#1.Clean column names
df.columns = df.columns.str.strip().str.replace(" ", "_").str.replace("(", "").str.replace(")", "")
print(" Cleaned Column Names:")
print(df.columns.tolist())

#2.Identify categorical & divide
categorical_cols = df.select_dtypes(include='object').columns.tolist()
# Print categorical columns
print("Categorical Columns:")
print(categorical_cols)
# Ordinal columns (with natural order)
ordinal_cols = ['Education', 'Dependents']
# Nominal columns (no natural order)
nominal_cols = [col for col in categorical_cols if col not in ordinal_cols]
# Print them
print("Ordinal Columns:", ordinal_cols)
print("Nominal Columns:", nominal_cols)

#3.Handle Missing Values
df[nominal_cols]=df[nominal_cols].fillna(df[nominal_cols].mode().iloc[0])
df[ordinal_cols]=df[ordinal_cols].fillna(df[ordinal_cols].mode().iloc[0])
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# 4.1 Fill numeric columns with median
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
# 4.2 Fill nominal columns with mode
df[nominal_cols] = df[nominal_cols].fillna(df[nominal_cols].mode().iloc[0])
# 4.3 Fill ordinal columns with mode
df[ordinal_cols] = df[ordinal_cols].fillna(df[ordinal_cols].mode().iloc[0])
# Verify missing values
print(" Missing Values After Filling:")
print(df.isnull().sum())

# 4.Ordinal Encoding
ord_enc = OrdinalEncoder()
df[ordinal_cols] = ord_enc.fit_transform(df[ordinal_cols])
# Print first 5 rows to verify
print("Ordinal Columns After Encoding:")
print(df[ordinal_cols].head())

#5.One-Hot Encoding for Nominal
df = pd.get_dummies(df, columns=nominal_cols, drop_first=True)
# Print first 5 rows to verify
print(" DataFrame After One-Hot Encoding Nominal Columns:")
print(df.head())

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 1. Load CSV
df = pd.read_csv("loan_approved.csv")

# 2. Clean column names
df.columns = df.columns.str.strip().str.replace(" ", "_").str.replace("(", "").str.replace(")", "")

# 3. Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns.tolist()
print("Categorical Columns:", categorical_cols)

# 4. Handle missing values
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())
df[categorical_cols] = df[categorical_cols].fillna(df[categorical_cols].mode().iloc[0])

# 5. Encode categorical columns

# 5.1 Label Encoding for binary columns (2 unique values)
binary_cols = [col for col in categorical_cols if df[col].nunique() == 2]
le = LabelEncoder()
df[binary_cols] = df[binary_cols].apply(lambda col: le.fit_transform(col))

# 5.2 One-Hot Encoding for multi-category columns (>2 unique values)
multi_cat_cols = [col for col in categorical_cols if df[col].nunique() > 2]
df = pd.get_dummies(df, columns=multi_cat_cols, drop_first=True)

# 6. Show first 5 rows of processed dataset
print("First 5 rows of preprocessed dataset:")
print(df.head())

import pandas as pd
from scipy.stats import zscore
df=pd.DataFrame({"Values": [10, 12, 15, 18, 20]})
df["Z_Score"]=zscore(df["Values"])
print(df)

import numpy as np
# Sample data
data=np.array([10,12,15,18,20])
# Calculate mean & std
mean=np.mean(data)
std=np.std(data)
# Calculate Z-score
z_scores=(data-mean)/std
print("Mean:", mean)
print("Standard Deviation:", std)
print("Z-Scores:", z_scores)

"""identify outliers using histogram , boxplot,then skewness

use decision based algorithms

data["CoapplicantIncome"].kurtosis ()

from sklearn.preprocessing import PowerTransformer
trans=PowerTransformer(method='yeo-johnson' )

la_trans=trans. fit_transform(data[["CoapplicantIncome"]])
la_trans.shape

print("skewness : ",pd.Series(la_trans.reshape(614,)).skew())
print("Kurtosis",pd.Series(la_trans.reshape(614,)).kurtosis())



"""

import numpy as np
import statsmodels.api as sm
import pylab as py

# np.random generates different random numbers everytime the code is executed.
data=np.random.rand(100)
sm.qqplot(data, line ='45') # data is not normally distirbuted.

py.show()

# Commented out IPython magic to ensure Python compatibility.
## importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline


## generating a random variable
exp=np.random.normal(25,15,1000)

import numpy as np
import pandas as pd

np.random.seed(42)

# Create Customer Dataset
data = pd.DataFrame({
    'CustomerID': range(1, 21),
    'Age': np.random.randint(18, 60, 20),
    'Annual_Income': np.random.randint(30000, 120000, 20),
    'Gender': np.random.choice(['Male', 'Female'], 20),
    'Region': np.random.choice(['North', 'South', 'East', 'West'], 20)
})

# Assign Spending Scores with different means for each region
data.loc[data['Region'] == 'North', 'Spending_Score'] = np.random.randint(60, 80, data[data['Region'] == 'North'].shape[0])
data.loc[data['Region'] == 'South', 'Spending_Score'] = np.random.randint(30, 50, data[data['Region'] == 'South'].shape[0])
data.loc[data['Region'] == 'East', 'Spending_Score'] = np.random.randint(40, 60, data[data['Region'] == 'East'].shape[0])
data.loc[data['Region'] == 'West', 'Spending_Score'] = np.random.randint(70, 90, data[data['Region'] == 'West'].shape[0])

data.head()

