# -*- coding: utf-8 -*-
"""Day-17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsjGkyuBQZ4r-bgl642C4U_i2aNcOx03
"""

import seaborn as sns

df1 = sns.load_dataset('tips')
df1.head()

import seaborn as sns

df = sns.load_dataset('taxis')
df.head()

df.info()

df.shape

df.describe()

df.columns

df.describe(include='object')

df.isna().sum()

(df.isna().sum()/df.shape[0])*100

((df.shape[0]- df.dropna().shape[0])/df.shape[0])*100

df=df.dropna()

df=df.reset_index(drop=True)

df.shape

df.describe()

df.isna().sum()

"""EDA

tip is the Target column

tip is numerical featue , analyze with color feature which categorical
"""

df.color.value_counts ()

"""Graphical analysis of categorical data"""

import matplotlib.pyplot as plt

sns.histplot(x=df.tip, hue=df.color, kde=True, palette={'yellow':'yellow','green' : 'green'})

sns.barplot(x=df.color, y=df.tip, estimator='mean' )

sns.histplot(x=df.tip,hue=df.color,kde=True,color=['green','yellow'])
plt.show()

sns.histplot(x=df.tip, hue=df.color, kde=True, palette={'yellow':'yellow','green' : 'green'})

"""**Hypotheses:**

. HO: distribution of tip for yellow = distribution of tip for green
. H1: distribution of tip for yellow # distribution of tip for green
"""

yellow_tip=df['tip'][df['color'] == 'yellow']
green_tip=df['tip'][df['color'] == 'green']

green_tip.shape

yellow_tip.shape

# Independent T-Test
from scipy import stats

t_stat, p_val = stats.ttest_ind(yellow_tip, green_tip)
#print("Independent T-Test statistic:", t_stat)
print("P-value:", p_val)

alpha = 0.05  # Significance level

if p_val < alpha:
    print("Reject null hypothesis: The tip for yellow category is different from that of green")
else:
    print("Fail to reject null hypothesis")

import seaborn as sns
from scipy import stats

# Load taxis dataset
df = sns.load_dataset('taxis')

# Separate tip amounts by payment method
credit_tip = df.loc[df['payment'] == 'credit card', 'tip']
cash_tip = df.loc[df['payment'] == 'cash', 'tip']

# Independent T-Test
t_stat, p_val = stats.ttest_ind(credit_tip, cash_tip)

print("Independent T-Test statistic:", t_stat)
print("P-value:", p_val)

alpha = 0.05  # significance level

if p_val < alpha:
    print("Reject null hypothesis: The tip for credit card payment is different from cash")
else:
    print("Fail to reject null hypothesis")

sns.barplot(x=df.payment,y=df.tip,estimator='mean')

import matplotlib.pyplot as plt
sns.histplot(x=df.tip,hue=df.payment,kde=True,palette={'green','yellow'})
plt.show()

sns.histplot(x=df.payment,hue=df.color,kde=True,palette={'green','yellow'})
plt.show()

sns.histplot(x=df.tip,hue=df.color,kde=True,palette={'green','yellow'})
plt.show()

df.color.value_counts()

df['pickup_borough'].unique()

df['pickup_borough' ]. value_counts ()

sns.barplot(x=df['pickup_borough' ], y=df['tip' ], palette='Set2')

df['tip' ].groupby (df['pickup_borough' ]) . mean ()

"""**Hypotheses:**

. HO: distribution of tip is the same across all pickup_borough categories

. H1: At least one category has a different distribution of tip
"""

df.info()

import pandas as pd
from statsmodels.stats.multicomp import pairwise_tukeyhsd

df_tukey = df[['tip', 'pickup_borough']].copy()

# Force correct types
df_tukey['tip'] = pd.to_numeric(df_tukey['tip'], errors='coerce')
df_tukey['pickup_borough'] = df_tukey['pickup_borough'].astype(str)

# Remove invalid rows
df_tukey = df_tukey.dropna()

# Remove empty strings if any
df_tukey = df_tukey[df_tukey['pickup_borough'].str.strip() != ""]

# Reset index
df_tukey.reset_index(drop=True, inplace=True)

# Tukey test
tukey = pairwise_tukeyhsd(
    endog=df_tukey['tip'].values,
    groups=df_tukey['pickup_borough'].values,
    alpha=0.05
)
print(tukey)

sns.barplot(x=df['pickup_borough'],y=df['tip'],palette='Set2',estimator='std')

sns.histplot(x=df['tip'],hue=df['pickup_borough'],bins=20,kde=True,palette='Set2')

# ANOVA Test
categories = [group['tip' ].values for name, group in df.groupby('pickup_zone')]

f_stat, p_val = stats.f_oneway(*categories)
#print("ANOVA F-statistic:", f_stat)
print("P-value:", p_val)
alpha=0.05
if p_val < alpha:
  print("Reject null hypothesis: ")
else:
  print("Fail to reject null hypothesis: ")

# ANOVA Test
categories = [group['tip' ]. values for name, group in df.groupby('dropoff_zone' ) ]

f_stat, p_val = stats.f_oneway(*categories)
#print("ANOVA F-statistic:", f stat)

print("P-value:", p_val)
alpha=0.05
if p_val < alpha:
  print("Reject null hypothesis: ")
else:
  print("Fail to reject null hypothesis: ")

from scipy import stats

# Pearson correlation
r, p_val = stats.pearsonr(df['tip'], df['fare'])

print("Correlation (r):", r)
print("P-value:", p_val)

alpha = 0.05

if p_val < alpha:
    print("Reject null hypothesis: There is a significant correlation between tip and fare")
else:
    print("Fail to reject null hypothesis: No significant correlation between tip and fare")

sns.histplot(df['passengers'],kde=True)
plt. show()

# Histogram for Tip
sns.histplot(df['tip'], kde=True)
plt.title("Histogram of Tip")
plt.xlabel("Tip")
plt.ylabel("Frequency")
plt.show()

sns.scatterplot(x=df['fare'], y=df['tip'], hue=df['payment'])
plt.show()

nm=df[['fare','tip','tolls','distance','passengers']]
sns.heatmap(nm.corr(),annot=True,cmap="Blues")

plt.figure(figsize=(12, 8))
# Select only numerical columns for correlation calculation
numeric_df = df.select_dtypes(include=['float64', 'int64'])
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title("Correlation Heatmap (Feature Relationships)")
plt.show()

sns.scatterplot(x=df.tip,y=df.passengers)